//
//  WordBank.swift
//  SpeechTrak
//
//  Created by Nick on 2/20/25.
//

import Foundation

struct WordBank {
    // Full list of hardcoded words
    static let words: [Word] = [
        //MARK: /p/ Sound
           Word(text: "pan", soundPositions: [.init(sound: .p, position: .beginning)]),
           Word(text: "pig", soundPositions: [.init(sound: .p, position: .beginning)]),
           Word(text: "pie", soundPositions: [.init(sound: .p, position: .beginning)]),
           Word(text: "pot", soundPositions: [.init(sound: .p, position: .beginning)]),
           Word(text: "pet", soundPositions: [.init(sound: .p, position: .beginning)]),
           Word(text: "apple", soundPositions: [.init(sound: .p, position: .middle)]),
           Word(text: "happy", soundPositions: [.init(sound: .p, position: .middle)]),
           Word(text: "open", soundPositions: [.init(sound: .p, position: .middle)]),
           Word(text: "puppy", soundPositions: [.init(sound: .p, position: .middle)]),
           Word(text: "paper", soundPositions: [.init(sound: .p, position: .middle)]),
           Word(text: "cap", soundPositions: [.init(sound: .p, position: .end)]),
           Word(text: "map", soundPositions: [.init(sound: .p, position: .end)]),
           Word(text: "hop", soundPositions: [.init(sound: .p, position: .end)]),
           Word(text: "sip", soundPositions: [.init(sound: .p, position: .end)]),
           Word(text: "top", soundPositions: [.init(sound: .p, position: .end)]),

           //MARK: /b/ Sound
           Word(text: "bat", soundPositions: [.init(sound: .b, position: .beginning)]),
           Word(text: "ball", soundPositions: [.init(sound: .b, position: .beginning)]),
           Word(text: "bee", soundPositions: [.init(sound: .b, position: .beginning)]),
           Word(text: "book", soundPositions: [.init(sound: .b, position: .beginning)]),
           Word(text: "bag", soundPositions: [.init(sound: .b, position: .beginning)]),
           Word(text: "baby", soundPositions: [.init(sound: .b, position: .middle)]),
           Word(text: "table", soundPositions: [.init(sound: .b, position: .middle)]),
           Word(text: "rabbit", soundPositions: [.init(sound: .b, position: .middle)]),
           Word(text: "cabbage", soundPositions: [.init(sound: .b, position: .middle)]),
           Word(text: "hobby", soundPositions: [.init(sound: .b, position: .middle)]),
           Word(text: "cab", soundPositions: [.init(sound: .b, position: .end)]),
           Word(text: "tub", soundPositions: [.init(sound: .b, position: .end)]),
           Word(text: "web", soundPositions: [.init(sound: .b, position: .end)]),
           Word(text: "grab", soundPositions: [.init(sound: .b, position: .end)]),
           Word(text: "blob", soundPositions: [.init(sound: .b, position: .end)]),

           //MARK: /t/ Sound
           Word(text: "top", soundPositions: [.init(sound: .t, position: .beginning)]),
           Word(text: "ten", soundPositions: [.init(sound: .t, position: .beginning)]),
           Word(text: "tiger", soundPositions: [.init(sound: .t, position: .beginning)]),
           Word(text: "turtle", soundPositions: [.init(sound: .t, position: .beginning)]),
           Word(text: "table", soundPositions: [.init(sound: .t, position: .beginning)]),
           Word(text: "water", soundPositions: [.init(sound: .t, position: .middle)]),
           Word(text: "butter", soundPositions: [.init(sound: .t, position: .middle)]),
           Word(text: "later", soundPositions: [.init(sound: .t, position: .middle)]),
           Word(text: "kitten", soundPositions: [.init(sound: .t, position: .middle)]),
           Word(text: "little", soundPositions: [.init(sound: .t, position: .middle)]),
           Word(text: "cat", soundPositions: [.init(sound: .t, position: .end)]),
           Word(text: "hat", soundPositions: [.init(sound: .t, position: .end)]),
           Word(text: "boat", soundPositions: [.init(sound: .t, position: .end)]),
           Word(text: "mat", soundPositions: [.init(sound: .t, position: .end)]),
           Word(text: "sit", soundPositions: [.init(sound: .t, position: .end)]),

           //MARK: /d/ Sound
           Word(text: "dog", soundPositions: [.init(sound: .d, position: .beginning)]),
           Word(text: "door", soundPositions: [.init(sound: .d, position: .beginning)]),
           Word(text: "duck", soundPositions: [.init(sound: .d, position: .beginning)]),
           Word(text: "doll", soundPositions: [.init(sound: .d, position: .beginning)]),
           Word(text: "day", soundPositions: [.init(sound: .d, position: .beginning)]),
           Word(text: "ladder", soundPositions: [.init(sound: .d, position: .middle)]),
           Word(text: "spider", soundPositions: [.init(sound: .d, position: .middle)]),
           Word(text: "daddy", soundPositions: [.init(sound: .d, position: .middle)]),
           Word(text: "muddy", soundPositions: [.init(sound: .d, position: .middle)]),
           Word(text: "shadow", soundPositions: [.init(sound: .d, position: .middle)]),
           Word(text: "bed", soundPositions: [.init(sound: .d, position: .end)]),
           Word(text: "red", soundPositions: [.init(sound: .d, position: .end)]),
           Word(text: "mad", soundPositions: [.init(sound: .d, position: .end)]),
           Word(text: "road", soundPositions: [.init(sound: .d, position: .end)]),
           Word(text: "seed", soundPositions: [.init(sound: .d, position: .end)]),
           
           //MARK: /s/ Sound
           Word(text: "sun", soundPositions: [.init(sound: .s, position: .beginning)]),
           Word(text: "sock", soundPositions: [.init(sound: .s, position: .beginning)]),
           Word(text: "soup", soundPositions: [.init(sound: .s, position: .beginning)]),
           Word(text: "sea", soundPositions: [.init(sound: .s, position: .beginning)]),
           Word(text: "sand", soundPositions: [.init(sound: .s, position: .beginning)]),
           Word(text: "messy", soundPositions: [.init(sound: .s, position: .middle)]),
           Word(text: "bison", soundPositions: [.init(sound: .s, position: .middle)]),
           Word(text: "pencil", soundPositions: [.init(sound: .s, position: .middle)]),
           Word(text: "lizard", soundPositions: [.init(sound: .s, position: .middle)]),
           Word(text: "castle", soundPositions: [.init(sound: .s, position: .middle)]),
           Word(text: "bus", soundPositions: [.init(sound: .s, position: .end)]),
           Word(text: "gas", soundPositions: [.init(sound: .s, position: .end)]),
           Word(text: "dress", soundPositions: [.init(sound: .s, position: .end)]),
           Word(text: "yes", soundPositions: [.init(sound: .s, position: .end)]),
           Word(text: "glass", soundPositions: [.init(sound: .s, position: .end)]),
           
           //MARK: /z/ Sound
           Word(text: "zoo", soundPositions: [.init(sound: .z, position: .beginning)]),
           Word(text: "zebra", soundPositions: [.init(sound: .z, position: .beginning)]),
           Word(text: "zero", soundPositions: [.init(sound: .z, position: .beginning)]),
           Word(text: "zipper", soundPositions: [.init(sound: .z, position: .beginning)]),
           Word(text: "zone", soundPositions: [.init(sound: .z, position: .beginning)]),
           Word(text: "lizard", soundPositions: [.init(sound: .z, position: .middle)]),
           Word(text: "desert", soundPositions: [.init(sound: .z, position: .middle)]),
           Word(text: "wizard", soundPositions: [.init(sound: .z, position: .middle)]),
           Word(text: "puzzle", soundPositions: [.init(sound: .z, position: .middle)]),
           Word(text: "razor", soundPositions: [.init(sound: .z, position: .middle)]),
           Word(text: "buzz", soundPositions: [.init(sound: .z, position: .end)]),
           Word(text: "jazz", soundPositions: [.init(sound: .z, position: .end)]),
           Word(text: "fuzz", soundPositions: [.init(sound: .z, position: .end)]),
           Word(text: "quiz", soundPositions: [.init(sound: .z, position: .end)]),
           Word(text: "nose", soundPositions: [.init(sound: .z, position: .end)]),
           
           //MARK: /ʃ/ ("sh") Sound
           Word(text: "shoe", soundPositions: [.init(sound: .sh, position: .beginning)]),
           Word(text: "ship", soundPositions: [.init(sound: .sh, position: .beginning)]),
           Word(text: "shark", soundPositions: [.init(sound: .sh, position: .beginning)]),
           Word(text: "sheep", soundPositions: [.init(sound: .sh, position: .beginning)]),
           Word(text: "shop", soundPositions: [.init(sound: .sh, position: .beginning)]),
           Word(text: "nation", soundPositions: [.init(sound: .sh, position: .middle)]),
           Word(text: "lotion", soundPositions: [.init(sound: .sh, position: .middle)]),
           Word(text: "ocean", soundPositions: [.init(sound: .sh, position: .middle)]),
           Word(text: "station", soundPositions: [.init(sound: .sh, position: .middle)]),
           Word(text: "caution", soundPositions: [.init(sound: .sh, position: .middle)]),
           Word(text: "fish", soundPositions: [.init(sound: .sh, position: .end)]),
           Word(text: "brush", soundPositions: [.init(sound: .sh, position: .end)]),
           Word(text: "wish", soundPositions: [.init(sound: .sh, position: .end)]),
           Word(text: "dish", soundPositions: [.init(sound: .sh, position: .end)]),
           Word(text: "cash", soundPositions: [.init(sound: .sh, position: .end)]),
           
           //MARK: /tʃ/ ("ch") Sound
           Word(text: "chair", soundPositions: [.init(sound: .ch, position: .beginning)]),
           Word(text: "cheese", soundPositions: [.init(sound: .ch, position: .beginning)]),
           Word(text: "chip", soundPositions: [.init(sound: .ch, position: .beginning)]),
           Word(text: "child", soundPositions: [.init(sound: .ch, position: .beginning)]),
           Word(text: "check", soundPositions: [.init(sound: .ch, position: .beginning)]),
           Word(text: "teacher", soundPositions: [.init(sound: .ch, position: .middle)]),
           Word(text: "nature", soundPositions: [.init(sound: .ch, position: .middle)]),
           Word(text: "ketchup", soundPositions: [.init(sound: .ch, position: .middle)]),
           Word(text: "pitcher", soundPositions: [.init(sound: .ch, position: .middle)]),
           Word(text: "feature", soundPositions: [.init(sound: .ch, position: .middle)]),
           Word(text: "beach", soundPositions: [.init(sound: .ch, position: .end)]),
           Word(text: "watch", soundPositions: [.init(sound: .ch, position: .end)]),
           Word(text: "peach", soundPositions: [.init(sound: .ch, position: .end)]),
           Word(text: "match", soundPositions: [.init(sound: .ch, position: .end)]),
           Word(text: "switch", soundPositions: [.init(sound: .ch, position: .end)]),
           
           //MARK: /dʒ/ ("j") Sound
           Word(text: "jump", soundPositions: [.init(sound: .j, position: .beginning)]),
           Word(text: "jelly", soundPositions: [.init(sound: .j, position: .beginning)]),
           Word(text: "juice", soundPositions: [.init(sound: .j, position: .beginning)]),
           Word(text: "jacket", soundPositions: [.init(sound: .j, position: .beginning)]),
           Word(text: "giraffe", soundPositions: [.init(sound: .j, position: .beginning)]),
           Word(text: "magic", soundPositions: [.init(sound: .j, position: .middle)]),
           Word(text: "engine", soundPositions: [.init(sound: .j, position: .middle)]),
           Word(text: "major", soundPositions: [.init(sound: .j, position: .middle)]),
           Word(text: "pigeon", soundPositions: [.init(sound: .j, position: .middle)]),
           Word(text: "budget", soundPositions: [.init(sound: .j, position: .middle)]),
           Word(text: "cage", soundPositions: [.init(sound: .j, position: .end)]),
           Word(text: "stage", soundPositions: [.init(sound: .j, position: .end)]),
           Word(text: "bridge", soundPositions: [.init(sound: .j, position: .end)]),
           Word(text: "badge", soundPositions: [.init(sound: .j, position: .end)]),
           Word(text: "edge", soundPositions: [.init(sound: .j, position: .end)]),
           
           //MARK: /m/ Sound
           Word(text: "moon", soundPositions: [.init(sound: .m, position: .beginning)]),
           Word(text: "man", soundPositions: [.init(sound: .m, position: .beginning)]),
           Word(text: "mouse", soundPositions: [.init(sound: .m, position: .beginning)]),
           Word(text: "map", soundPositions: [.init(sound: .m, position: .beginning)]),
           Word(text: "mom", soundPositions: [.init(sound: .m, position: .beginning)]),
           Word(text: "lemon", soundPositions: [.init(sound: .m, position: .middle)]),
           Word(text: "hammer", soundPositions: [.init(sound: .m, position: .middle)]),
           Word(text: "camel", soundPositions: [.init(sound: .m, position: .middle)]),
           Word(text: "tummy", soundPositions: [.init(sound: .m, position: .middle)]),
           Word(text: "summer", soundPositions: [.init(sound: .m, position: .middle)]),
           Word(text: "home", soundPositions: [.init(sound: .m, position: .end)]),
           Word(text: "game", soundPositions: [.init(sound: .m, position: .end)]),
           Word(text: "drum", soundPositions: [.init(sound: .m, position: .end)]),
           Word(text: "team", soundPositions: [.init(sound: .m, position: .end)]),
           Word(text: "poem", soundPositions: [.init(sound: .m, position: .end)]),

           //MARK: /n/ Sound
           Word(text: "nose", soundPositions: [.init(sound: .n, position: .beginning)]),
           Word(text: "net", soundPositions: [.init(sound: .n, position: .beginning)]),
           Word(text: "nail", soundPositions: [.init(sound: .n, position: .beginning)]),
           Word(text: "nest", soundPositions: [.init(sound: .n, position: .beginning)]),
           Word(text: "night", soundPositions: [.init(sound: .n, position: .beginning)]),
           Word(text: "dinner", soundPositions: [.init(sound: .n, position: .middle)]),
           Word(text: "tiny", soundPositions: [.init(sound: .n, position: .middle)]),
           Word(text: "planet", soundPositions: [.init(sound: .n, position: .middle)]),
           Word(text: "bunny", soundPositions: [.init(sound: .n, position: .middle)]),
           Word(text: "winner", soundPositions: [.init(sound: .n, position: .middle)]),
           Word(text: "pen", soundPositions: [.init(sound: .n, position: .end)]),
           Word(text: "sun", soundPositions: [.init(sound: .n, position: .end)]),
           Word(text: "run", soundPositions: [.init(sound: .n, position: .end)]),
           Word(text: "man", soundPositions: [.init(sound: .n, position: .end)]),
           Word(text: "fan", soundPositions: [.init(sound: .n, position: .end)]),

           //MARK: /ŋ/ ("ng") Sound
           Word(text: "singer", soundPositions: [.init(sound: .ng, position: .middle)]),
           Word(text: "finger", soundPositions: [.init(sound: .ng, position: .middle)]),
           Word(text: "hanger", soundPositions: [.init(sound: .ng, position: .middle)]),
           Word(text: "longer", soundPositions: [.init(sound: .ng, position: .middle)]),
           Word(text: "banger", soundPositions: [.init(sound: .ng, position: .middle)]),
           Word(text: "ring", soundPositions: [.init(sound: .ng, position: .end)]),
           Word(text: "sing", soundPositions: [.init(sound: .ng, position: .end)]),
           Word(text: "king", soundPositions: [.init(sound: .ng, position: .end)]),
           Word(text: "wing", soundPositions: [.init(sound: .ng, position: .end)]),
           Word(text: "thing", soundPositions: [.init(sound: .ng, position: .end)]),

           //MARK: /l/ Sound
           Word(text: "lion", soundPositions: [.init(sound: .l, position: .beginning)]),
           Word(text: "lamp", soundPositions: [.init(sound: .l, position: .beginning)]),
           Word(text: "leaf", soundPositions: [.init(sound: .l, position: .beginning)]),
           Word(text: "love", soundPositions: [.init(sound: .l, position: .beginning)]),
           Word(text: "lemon", soundPositions: [.init(sound: .l, position: .beginning)]),
           Word(text: "pillow", soundPositions: [.init(sound: .l, position: .middle)]),
           Word(text: "salad", soundPositions: [.init(sound: .l, position: .middle)]),
           Word(text: "balloon", soundPositions: [.init(sound: .l, position: .middle)]),
           Word(text: "yellow", soundPositions: [.init(sound: .l, position: .middle)]),
           Word(text: "hello", soundPositions: [.init(sound: .l, position: .middle)]),
           Word(text: "ball", soundPositions: [.init(sound: .l, position: .end)]),
           Word(text: "pool", soundPositions: [.init(sound: .l, position: .end)]),
           Word(text: "fall", soundPositions: [.init(sound: .l, position: .end)]),
           Word(text: "bell", soundPositions: [.init(sound: .l, position: .end)]),
           Word(text: "hill", soundPositions: [.init(sound: .l, position: .end)]),

           //MARK: /r/ Sound
           Word(text: "rabbit", soundPositions: [.init(sound: .r, position: .beginning)]),
           Word(text: "red", soundPositions: [.init(sound: .r, position: .beginning)]),
           Word(text: "rose", soundPositions: [.init(sound: .r, position: .beginning)]),
           Word(text: "road", soundPositions: [.init(sound: .r, position: .beginning)]),
           Word(text: "rain", soundPositions: [.init(sound: .r, position: .beginning)]),
           Word(text: "carrot", soundPositions: [.init(sound: .r, position: .middle)]),
           Word(text: "berry", soundPositions: [.init(sound: .r, position: .middle)]),
           Word(text: "pirate", soundPositions: [.init(sound: .r, position: .middle)]),
           Word(text: "syrup", soundPositions: [.init(sound: .r, position: .middle)]),
           Word(text: "mirror", soundPositions: [.init(sound: .r, position: .middle)]),
           Word(text: "car", soundPositions: [.init(sound: .r, position: .end)]),
           Word(text: "star", soundPositions: [.init(sound: .r, position: .end)]),
           Word(text: "bear", soundPositions: [.init(sound: .r, position: .end)]),
           Word(text: "butter", soundPositions: [.init(sound: .r, position: .end)]),
           Word(text: "door", soundPositions: [.init(sound: .r, position: .end)]),
           
           //MARK: /w/ Sound
           Word(text: "water", soundPositions: [.init(sound: .w, position: .beginning)]),
           Word(text: "whale", soundPositions: [.init(sound: .w, position: .beginning)]),
           Word(text: "window", soundPositions: [.init(sound: .w, position: .beginning)]),
           Word(text: "wing", soundPositions: [.init(sound: .w, position: .beginning)]),
           Word(text: "wagon", soundPositions: [.init(sound: .w, position: .beginning)]),
           Word(text: "flower", soundPositions: [.init(sound: .w, position: .middle)]),
           Word(text: "power", soundPositions: [.init(sound: .w, position: .middle)]),
           Word(text: "tower", soundPositions: [.init(sound: .w, position: .middle)]),
           Word(text: "sandwich", soundPositions: [.init(sound: .w, position: .middle)]),
           Word(text: "award", soundPositions: [.init(sound: .w, position: .middle)]),
           // /w/ in the end is rare and typically not included

           //MARK: /j/ ("y") Sound
           Word(text: "yes", soundPositions: [.init(sound: .y, position: .beginning)]),
           Word(text: "yellow", soundPositions: [.init(sound: .y, position: .beginning)]),
           Word(text: "yogurt", soundPositions: [.init(sound: .y, position: .beginning)]),
           Word(text: "yawn", soundPositions: [.init(sound: .y, position: .beginning)]),
           Word(text: "yard", soundPositions: [.init(sound: .y, position: .beginning)]),
           Word(text: "onion", soundPositions: [.init(sound: .y, position: .middle)]),
           Word(text: "canyon", soundPositions: [.init(sound: .y, position: .middle)]),
           Word(text: "lawyer", soundPositions: [.init(sound: .y, position: .middle)]),
           Word(text: "millionaire", soundPositions: [.init(sound: .y, position: .middle)]),
           Word(text: "accordion", soundPositions: [.init(sound: .y, position: .middle)]),
           // /j/ typically doesn’t occur in the end position

           //MARK: /h/ Sound
           Word(text: "hat", soundPositions: [.init(sound: .h, position: .beginning)]),
           Word(text: "house", soundPositions: [.init(sound: .h, position: .beginning)]),
           Word(text: "horse", soundPositions: [.init(sound: .h, position: .beginning)]),
           Word(text: "hand", soundPositions: [.init(sound: .h, position: .beginning)]),
           Word(text: "happy", soundPositions: [.init(sound: .h, position: .beginning)]),
           Word(text: "ahead", soundPositions: [.init(sound: .h, position: .middle)]),
           Word(text: "behave", soundPositions: [.init(sound: .h, position: .middle)]),
           Word(text: "inhale", soundPositions: [.init(sound: .h, position: .middle)]),
           Word(text: "rehearse", soundPositions: [.init(sound: .h, position: .middle)]),
           Word(text: "behind", soundPositions: [.init(sound: .h, position: .middle)]),
           // /h/ does not typically occur in the end position
    ]
}

// Helper for indexing
struct SoundPositionKey: Hashable {
    let sound: SpeechSound
    let position: SoundPosition
}
